CommandParseException: add additional line breaks to improve formatting
 - if the commandString was only one word and on the same line as the
   ``` markdown interpreted it as the language description and
   omitted the word; adding a linebreak after ``` fixes this